# Generated by Django 4.1.6 on 2023-03-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_alter_postmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='media/image/'),
        ),
    ]
